version: 0.0
os: linux
files:
  - source: /ROOT.war
    destination:  /var/lib/tomcat8/webapps/
hooks:
  ApplicationStop:
    - location: application_stop.sh
      timeout: 120
  ApplicationStart:
    - location: application_start.sh
      timeout: 120