version: 0.0
os: linux
files:
  - source: /website.war
    destination: /usr/share/tomcat8/webapps/ROOT.war
hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 60
  ApplicationStart:
    - location: application_start.sh
      timeout: 60