version: 0.0
os: linux
files:
  - source: /
    destination: /
hooks:
  ApplicationStop:
    - location: application_stop.sh
      timeout: 60
  ApplicationStart:
    - location: application_start.sh
      timeout: 60