version: 0.0
os: linux
files:
  - source: /website.war
    destination: /usr/share/tomcat8/webapps/ROOT.war
hooks:
  ApplicationStop:
    - location: application_stop.sh
      timeout: 120
  ApplicationStart:
    - location: application_start.sh
      timeout: 120